cmake_minimum_required(VERSION 3.30)
project(100DaysOfCode C)

set(CMAKE_C_STANDARD 11)

add_subdirectory(Day1)
add_subdirectory(Day2)
add_subdirectory(Day3)
add_subdirectory(Day4)
add_subdirectory(Day5)
add_subdirectory(Day6)
add_subdirectory(Day7)
add_subdirectory(Day8)
add_subdirectory(Day9)
add_subdirectory(Day10)
add_subdirectory(Day11)
add_subdirectory(Day12)
add_subdirectory(Day13)
add_subdirectory(Day14)
add_subdirectory(Day15)
add_subdirectory(Day16)
add_subdirectory(Day17)
add_subdirectory(Day18)
add_subdirectory(Day19)
add_subdirectory(Day20)
add_subdirectory(Day21)
add_subdirectory(Day22)
add_subdirectory(Day23)
add_subdirectory(Day24)
add_subdirectory(Day25)
add_subdirectory(Day26)
add_subdirectory(Day27)
add_subdirectory(Day28)
add_subdirectory(Day29)
add_subdirectory(Day30)
add_subdirectory(Day31)
add_subdirectory(Day32)
add_subdirectory(Day33)
add_subdirectory(Day34)
add_subdirectory(Day35)
add_subdirectory(Day36)
add_subdirectory(Day37)
add_subdirectory(Day38)
add_subdirectory(Day39)
add_subdirectory(Day40)
add_subdirectory(Day41)
add_subdirectory(Day42)
add_subdirectory(Day43)
add_subdirectory(Day44)
add_subdirectory(Day45)
add_subdirectory(Day46)
add_subdirectory(Day47)
add_subdirectory(Day48)
add_subdirectory(Day49)
add_subdirectory(Day50)
add_subdirectory(Day51)
add_subdirectory(Day52)
add_subdirectory(Day53)
add_subdirectory(Day54)
add_subdirectory(Day55)
add_subdirectory(Day56)
add_subdirectory(Day57)
add_subdirectory(Day58)
add_subdirectory(Day59)
add_subdirectory(Day60)
add_subdirectory(Day61)
add_subdirectory(Day62)
add_subdirectory(Day63)
add_subdirectory(Day64)
add_subdirectory(Day65)
add_subdirectory(Day66)
add_subdirectory(Day67)
add_subdirectory(Day68)
add_subdirectory(Day69)
add_subdirectory(Day70)
add_subdirectory(Day71)
add_subdirectory(Day72)
add_subdirectory(Day73)
add_subdirectory(Day74)
add_subdirectory(Day75)
add_subdirectory(Day76)
add_subdirectory(Day77)
add_subdirectory(Day78)
add_subdirectory(Day79)
add_subdirectory(Day80)
add_subdirectory(Day81)
add_subdirectory(Day82)
add_subdirectory(Day83)
add_subdirectory(Day84)
add_subdurectory(Day85)








